Many random packages update/upgrade.

diff --git a/mysql/receipt b/mysql/receipt
--- a/mysql/receipt
+++ b/mysql/receipt
@@ -1,34 +1,29 @@
-# SliTaz package receipt.
+# SliTaz package receipt v2.
 
 PACKAGE="mysql"
-VERSION="5.5.27"
-CATEGORY="office"
-SHORT_DESC="SQL database system."
+VERSION="5.5.56"
+CATEGORY="database"
+SHORT_DESC="SQL database system"
 MAINTAINER="pascal.bellard@slitaz.org"
 LICENSE="GPL2"
 WEB_SITE="https://www.mysql.com/"
-CONFIG_FILES="/etc/mysql"
-DATABASE_FILES="/var/lib/mysql"
-TAZPANEL_DAEMON="man|edit::/etc/mysql/my.cnf|options|web::$WEB_SITE"
-CROSS="bug: can not run test programm"
+#CROSS="bug: can not run test programm"
 
 TARBALL="$PACKAGE-$VERSION.tar.gz"
 WGET_URL="ftp://mirror.switch.ch/mirror/mysql/Downloads/MySQL-${VERSION%.*}/$TARBALL"
 
-DEPENDS="libmysqlclient mysql-client slitaz-base-files \
-libcrypto libssl ncurses zlib"
 BUILD_DEPENDS="cmake openssl-dev zlib-dev ncurses-dev readline-dev"
-SPLIT="mysql-client mysql-test mysql-dev libmysqlclient"
+SPLIT="libmysqlclient mysql-client mysql-test mysql-dev"
 
 # Rules to configure and make the package.
 compile_rules()
 {
-	mkdir -p $WOK/$PACKAGE/source/build
-	cd $WOK/$PACKAGE/source/build
+	mkdir build; cd build
+
 	# CFLAGS/CXXFLAGS as suggested upstream
 	CFLAGS="-fPIC ${CFLAGS} -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer" \
 	CXXFLAGS="-fPIC ${CXXFLAGS} -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors -fno-rtti" \
-	cmake ../$PACKAGE-$VERSION \
+	cmake .. \
 		-DCMAKE_BUILD_TYPE=Release \
 		-DCMAKE_INSTALL_PREFIX=/usr \
 		-DSYSCONFDIR=/etc/mysql \
@@ -61,46 +56,75 @@ compile_rules()
 		-DWITHOUT_BLACKHOLE_STORAGE_ENGINE=1 \
 		-DWITHOUT_FEDERATED_STORAGE_ENGINE=1 &&
 	make && make DESTDIR=$DESTDIR install
+
+	# fix paths
+	mv $install/usr/mysql-test $install/usr/share/mysql-test
+	mv $install/usr/sql-bench  $install/usr/share/sql-bench
+
+	# Configuration file
+	mkdir -p $install/etc
+	cp -a $stuff/etc/init.d $install/etc
+	cp -a $stuff/etc/mysql  $install/etc
+	chown -R root:root $install/etc
 }
 
 # Rules to gen a SliTaz package suitable for Tazpkg.
 genpkg_rules()
 {
-	mkdir -p \
-		$fs/usr/share \
-		$fs/usr/lib/mysql/plugin \
-		$fs/etc/mysql \
-		$fs/etc/mysql.d \
-		$fs/var/lib/mysql
+	# client binaries (plus /usr/bin/mysql), see $src/build/client
+	client="mysql_plugin mysql_upgrade mysqladmin mysqlbinlog mysqlcheck \
+	mysqldump mysqlimport mysqlshow mysqlslap mysqltest"
 
-	cp -a $install/usr/bin $fs/usr
-	cp -a $install/usr/lib/mysql/plugin/*.so* $fs/usr/lib/mysql/plugin
-	cp -a $install/usr/share/mysql $fs/usr/share
-
-	# Configuration file
-	cp -a $stuff/etc/init.d $fs/etc
-	cp -a $stuff/etc/mysql $fs/etc
-	grep -q "bind-address" $fs/etc/mysql/my.cnf || sed -i \
-		's/^\[mysqld\]/[mysqld]\nbind-address\t= 127.0.0.1/' \
-		$fs/etc/mysql/my.cnf
-
-	# Permissions
-	chmod 600 $fs/etc/mysql/my.cnf
-
-	cat $stuff/*.files-list | while read file; do
-		[ -f $fs$file ] && rm -f $fs$file
-	done
-
+	case $PACKAGE in
+		mysql)
+			copy etc/ bin/ plugin/ /usr/share/mysql/
+			for i in $client mysql mysql_config; do
+				rm $fs/usr/bin/$i
+			done
+			find $fs -name '*.m4' -delete
+			DEPENDS="libmysqlclient mysql-client slitaz-base-files \
+			libcrypto libssl ncurses zlib"
+			CONFIG_FILES="/etc/mysql"
+			DATABASE_FILES="/var/lib/mysql"
+			TAZPANEL_DAEMON="man|edit::/etc/mysql/my.cnf|options|web::$WEB_SITE"
+			;;
+		libmysqlclient)
+			copy libmysqlclient*so*
+			CAT="database|client libraries"
+			DEPENDS="libcrypto libssl zlib"
+			;;
+		mysql-client)
+			copy /bin/mysql $client
+			CAT="database|client files"
+			PROVIDE="mysql_or_postgresql"
+			DEPENDS="libmysqlclient   libcrypto libssl ncurses zlib"
+			;;
+		mysql-test)
+			copy mysql-test/ sql-bench/ db.opt
+			CAT="development|tests and benchmarks"
+			DEPENDS="mysql perl"
+			;;
+		*-dev)
+			copy @dev mysql_config
+			rm -r $fs/usr/share/mysql-test
+			;;
+	esac
 }
 
 # Pre and post install commands for Tazpkg.
-post_install()
+pre_install_mysql()
 {
-	local user
-	local group
+	# Cleanup old files
+	rm -f "$1/usr/libexec/mysql"*
+	# Move old config
+	[ -f "$1/etc/my.cnf" ] && mv -f "$1/etc/my.cnf" "$1/etc/mysql/my.cnf"
+}
 
-	user=mysql
-	group=mysql
+post_install_mysql()
+{
+	chmod 600 "$1/etc/mysql/my.cnf"
+
+	local user=mysql group=mysql
 
 	if ! grep -q $user "$1/etc/passwd"; then
 		action "Adding user/group $user..."
@@ -109,36 +133,36 @@ post_install()
 		status
 	fi
 	# adduser mysql if needed
-	if ! grep -q ${user} "$1/etc/passwd"; then
-		action "Adding user MySQL..."
+	if ! grep -q $user "$1/etc/passwd"; then
+		action "Adding MySQL Daemon user..."
 		chroot "$1/" /bin/adduser -s /bin/false -h /dev/null \
-			-g "MySQL Daemon user" -u 27 -H -D -S -G ${group} ${user}
+			-g "MySQL Daemon user" -u 27 -H -D -S -G $group $user
 		status
 	fi
-	#chroot "$1/" /bin/chown ${user}.${group} $(cat "$1/$INSTALLED/$PACKAGE/files.list")
-	chroot "$1/" /bin/chown -R ${user}.${group} /var/lib/mysql
-	chroot "$1/" mysql_install_db --user=${user} --basedir=/usr
+	#chroot "$1/" /bin/chown $user.$group $(cat "$1/$INSTALLED/$PACKAGE/files.list")
+	mkdir -p "$1/var/lib/mysql"
+	chroot "$1/" /bin/chown -R $user.$group /var/lib/mysql
+	chroot "$1/" mysql_install_db --user=$user --basedir=/usr
+
 	[ -n "$quiet" ] || cat <<EOF
 ----
-To start $PACKAGE server you can run :
+To start mysql server you can run:
 
-    /etc/init.d/$PACKAGE start
+    /etc/init.d/mysql start
 
-Or add $PACKAGE to RUN_DAEMONS in /etc/rcS.conf
+Or add mysql to RUN_DAEMONS in /etc/rcS.conf
 ----
 EOF
 }
 
-pre_install()
-{
-	# Cleanup old files
-	rm -f "$1/usr/libexec/mysql"*
-	# Mv config
-	[ -f "$1/etc/my.cnf" ] && mv -f "$1/etc/my.cnf" "$1/etc/mysql/my.cnf"
-}
-
-post_remove()
+post_remove_mysql()
 {
 	echo "Removing user/group mysql"
 	chroot "$1/" deluser mysql
+}
+
+post_install_mysql_test()
+{
+	chmod 2777 "$1/usr/share/mysql-test"
+	chmod 2777 "$1/usr/share/sql-bench"
 }
